// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountUserAccounts(ctx context.Context, userID string) (int64, error)
	CountUserSessions(ctx context.Context, userID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerification(ctx context.Context, arg CreateVerificationParams) (Verification, error)
	DeleteAccount(ctx context.Context, id string) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteExpiredVerifications(ctx context.Context) error
	DeleteUser(ctx context.Context, id string) error
	DeleteUserAccounts(ctx context.Context, userID string) error
	DeleteUserVerifications(ctx context.Context, identifier string) error
	DeleteVerification(ctx context.Context, id string) error
	DeleteVerificationByIdentifier(ctx context.Context, identifier string) error
	GetAccountByID(ctx context.Context, id string) (Account, error)
	GetAccountByProvider(ctx context.Context, arg GetAccountByProviderParams) (Account, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetSessionByToken(ctx context.Context, token string) (Session, error)
	GetSessionWithUser(ctx context.Context, token string) (GetSessionWithUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserCredentialAccount(ctx context.Context, userID string) (Account, error)
	GetVerificationByID(ctx context.Context, id string) (Verification, error)
	GetVerificationByIdentifier(ctx context.Context, identifier string) (Verification, error)
	GetVerificationByValue(ctx context.Context, value string) (Verification, error)
	LinkAccount(ctx context.Context, arg LinkAccountParams) (Account, error)
	ListActiveSessions(ctx context.Context, userID string) ([]Session, error)
	ListUserAccounts(ctx context.Context, userID string) ([]Account, error)
	ListUserSessions(ctx context.Context, userID string) ([]Session, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RevokeOtherSessions(ctx context.Context, arg RevokeOtherSessionsParams) error
	RevokeSession(ctx context.Context, id string) error
	RevokeSessionByToken(ctx context.Context, token string) error
	RevokeUserSessions(ctx context.Context, userID string) error
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) (Account, error)
	UnlinkAccount(ctx context.Context, arg UnlinkAccountParams) error
	UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) (Account, error)
	UpdateAccountTokens(ctx context.Context, arg UpdateAccountTokensParams) (Account, error)
	UpdateSessionExpiry(ctx context.Context, arg UpdateSessionExpiryParams) (Session, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error)
	ValidateVerification(ctx context.Context, arg ValidateVerificationParams) (Verification, error)
	VerifyUserEmail(ctx context.Context, id string) (User, error)
}

var _ Querier = (*Queries)(nil)
