// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification.sql

package sqlc

import (
	"context"
	"time"
)

const createVerification = `-- name: CreateVerification :one
INSERT INTO "verification" (id, identifier, value, expires_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, identifier, value, expires_at, created_at, updated_at
`

type CreateVerificationParams struct {
	ID         string    `json:"id"`
	Identifier string    `json:"identifier"`
	Value      string    `json:"value"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) (Verification, error) {
	row := q.db.QueryRow(ctx, createVerification,
		arg.ID,
		arg.Identifier,
		arg.Value,
		arg.ExpiresAt,
	)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Value,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredVerifications = `-- name: DeleteExpiredVerifications :exec
DELETE FROM "verification" WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredVerifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredVerifications)
	return err
}

const deleteUserVerifications = `-- name: DeleteUserVerifications :exec
DELETE FROM "verification" WHERE identifier = $1
`

func (q *Queries) DeleteUserVerifications(ctx context.Context, identifier string) error {
	_, err := q.db.Exec(ctx, deleteUserVerifications, identifier)
	return err
}

const deleteVerification = `-- name: DeleteVerification :exec
DELETE FROM "verification" WHERE id = $1
`

func (q *Queries) DeleteVerification(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteVerification, id)
	return err
}

const deleteVerificationByIdentifier = `-- name: DeleteVerificationByIdentifier :exec
DELETE FROM "verification" WHERE identifier = $1
`

func (q *Queries) DeleteVerificationByIdentifier(ctx context.Context, identifier string) error {
	_, err := q.db.Exec(ctx, deleteVerificationByIdentifier, identifier)
	return err
}

const getVerificationByID = `-- name: GetVerificationByID :one
SELECT id, identifier, value, expires_at, created_at, updated_at FROM "verification" WHERE id = $1
`

func (q *Queries) GetVerificationByID(ctx context.Context, id string) (Verification, error) {
	row := q.db.QueryRow(ctx, getVerificationByID, id)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Value,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVerificationByIdentifier = `-- name: GetVerificationByIdentifier :one
SELECT id, identifier, value, expires_at, created_at, updated_at FROM "verification"
WHERE identifier = $1 AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetVerificationByIdentifier(ctx context.Context, identifier string) (Verification, error) {
	row := q.db.QueryRow(ctx, getVerificationByIdentifier, identifier)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Value,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVerificationByValue = `-- name: GetVerificationByValue :one
SELECT id, identifier, value, expires_at, created_at, updated_at FROM "verification"
WHERE value = $1 AND expires_at > NOW()
`

func (q *Queries) GetVerificationByValue(ctx context.Context, value string) (Verification, error) {
	row := q.db.QueryRow(ctx, getVerificationByValue, value)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Value,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const validateVerification = `-- name: ValidateVerification :one
SELECT id, identifier, value, expires_at, created_at, updated_at FROM "verification"
WHERE identifier = $1 AND value = $2 AND expires_at > NOW()
`

type ValidateVerificationParams struct {
	Identifier string `json:"identifier"`
	Value      string `json:"value"`
}

func (q *Queries) ValidateVerification(ctx context.Context, arg ValidateVerificationParams) (Verification, error) {
	row := q.db.QueryRow(ctx, validateVerification, arg.Identifier, arg.Value)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Value,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
